### PR TITLE
Fixed #106, #109, #116: Donate Lightbox, Organization Section, indentation.

### LINKED ISSUE #106: Organisation Section : Weird Behavior on Clicking.
On the Supporting Organisation Sections , on clicking the fa-expand icon , the div overlaps the next section content. Happens in both homepage and /openinitiative/ page.

I can work on it. What should happen ideally?

### LINKED ISSUE #109: Paypal close button doesn't work
The close button of the Paypal pop-up doesn't work.
This needs to be fixed.
I would like to work on this.

### LINKED ISSUE #116: Weird Alignment Issue of Donate Lightbox
### Problem :
There is weird alignment on the Donate Lightbox and it is also not responsive.

#### I am working on it.

### PR DESCRIPTION
**Pull request by duttaditya18**
* Fixed close button of Donate Lightbox.
* Fixed weird alignment of Donate Lightbox and made it responsive.
* Fixed Indentation of `spread.html`
* Fixed Organization's arrow's weird behaviour on clicking.
* Fixes #106 
* Fixes #109 
* Fixes #116 

***I cannot give preview link. But I did all the changes in Firefox Dev Tools and they work.***

### CODE REVIEW

**Comment by duttaditya18** [comment]
Ping @Kreijstal @mariobehling @fossasia/public-code-admins

**Comment by 0x48piraj** [comment]
@naveentherocker You approved even when a valid PR was not filed !

**Comment by duttaditya18** [comment]
@Remorax So I would have to compile this? All right.

**Comment by mariobehling** [comment]
@duttaditya18 Please make a new PR taking the recent changes into account. Please separate issues, that don't belong to the same category/topic. Cheers.

**Pull request closed without merging**
