### PR TITLE
Hindi translation added

### LINKED ISSUE #66: Hindi translation not working
On clicking Hindi translation, the site doesn't translate it. Instead it shows the page in English only.
Hindi translation needs to be added.
I would like to work on this :)

### PR DESCRIPTION
**Pull request by Remorax**
Completely Fixes #66 
Hindi Translation works fine now.
Please review :)

### CODE REVIEW

**Comment by sayak119** [comment]
@Remorax Please resolve merge conflicts.

**Comment by mariobehling** [comment]
Looks like the translations are incomplete, particularly the Open Initiative letter. Please help to do it.

**Comment by Remorax** [comment]
Sure, I'll do it :)

**Comment by mariobehling** [comment]
Thanks! The content of https://github.com/fossasia/publiccode.asia/blob/master/site/content/openinitiative.en.md is still missing. Please copy that content and translate it as well. Cheers!

**Comment by mariobehling** [comment]
Merging this as work in progress.

**Comment by Remorax** [comment]
@mariobehling Do I have to copy the content of openinitiative.en.md to openinitiative.hi.md and then translate it?

**Pull request merged**
