### PR TITLE
Polish translation added Fixes #69

### LINKED ISSUE #69: Add Polish translation
# Goal
Polish translation added to the website.

# Right now
Currently there is no Polish language on the website.

# So...?
I'm ready to start working on Polish translation as soon as my previous PR will be merged 😄

### PR DESCRIPTION
**Pull request by kubami9**
**Added following Polish translations:**
 - imprint
 - openeinitiative
 - all-signatures
 - confirm
 - success
 - privacy
 - share/all files
 - strings

Also added "pl" into build.sh

### CODE REVIEW

**Comment by kubami9** [comment]
Travis failed but I don't know why :/

**Comment by mariobehling** [comment]
Travis build is failing. Please check.

**Comment by kubami9** [comment]
I checked previous translation commits and I left build.sh as it is, Travis test passed :)

**Comment by kubami9** [comment]
@sayak119 my bad, I'm gonna ad linkedin yaml as soon as I can, and I added pl to build.sh like in the docs but it crashed all website and failed Travis test so I turned it back as it was

**Comment by kubami9** [comment]
@Kreijstal good one 😄

**Comment by sayak119** [comment]
screenshot from 2017-12-14 02-06-07

@kubami9 Polish translation isn't showing up. Can you please check

**Comment by kubami9** [comment]
@sayak119 hmm... it looks like I missed something in one file. I think the reason may the build.sh file which I left with no changes because it was causing errors and wasn't passing Travis tests. I just tried to add "pl" to the line with translations and fire local server and it shows me: `Error: While parsing config: (1677, 2): duplicated tables`
parsing_error

**Pull request merged**
