### PR TITLE
Fixes #136 : refactored entire codebase

### LINKED ISSUE #136: Code Needs to be formatted
There are instances where the code is unstructured and needs to be refactored.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
#Entired Codebase Refactored 🎇 

- [X] CSS Files styles
- [X] Javascript sheets refactored (minified untouched)
- [X] HTML space issues solved
- [X] Added `linux` os type in linux

Fixes  #136

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
@mariobehling @fossasia/web-developers

**Comment by YashKumarVerma** [comment]
@Kreijstal @hpdang 
Pending since long. Apologies to bug.

**Comment by YashKumarVerma** [comment]
@fossasia/public-code-admins

**Comment by anshumanv** [comment]
Is it possible to provide a test link?

**Comment by YashKumarVerma** [comment]
@anshumanv , sure. deploying on surge

**Comment by YashKumarVerma** [comment]
image
@anshumanv

**Pull request merged**
